name: capp_telegram_news_bot_nim
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Bot-Build-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential musl musl-dev musl-tools openssl sqlite3 libsqlite3-dev libpcre3 upx-ucl strip-nondeterminism binutils
      - name: pull code
        uses: actions/checkout@main
      - name: Install nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.0' # default is 'stable'
          
#       - name: Build
#         run: |
#           nimble build -Y
#           nimble test -Y
          
#       - name: Install nim
#         run: |
#           curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
#           export PATH=/home/runner/.nimble/bin:$PATH
#           nim --version
#           nimble --version
#           nimble install
      - name: Run build script
        run: |
          export PATH=/home/runner/.nimble/bin:$PATH
          nimble install -Y
          ./build.sh
        shell: bash
      - name: Testing
        if: ${{ success() }}
        run: ./capp_telegram_news_bot_nim
        
