name: capp_telegram_news_bot_nim
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: |
          curl https://nim-lang.org/choosenim/init.sh -sSf | sh
          export PATH="~/.nimble/bin:$PATH"
          sudo apt-get update
          sudo apt-get install musl musl-dev openssl sqlite3 libsqlite3-dev libpcre3 
      - name: Run build script
        run: ./build.sh
        shell: bash
      - name: Testing
        if: ${{ success() }}
        
